# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks 
repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest tests/
        args: ["--maxfail=1", "--disable-warnings", "-q"]
        language: system
        types: [python]